name: Nightly Packaging

on:
  push:
    branches: [ ext-load ]

jobs:
  clasp_ubuntu_jammy:
    name: Clasp on Ubuntu Jammy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --build=binary --no-sign
          docker-image: ubuntu:jammy
          extra-build-deps: ca-certificates
      - uses: actions/upload-artifact@v3
        with:
          name: clasp-cl_1.0.0_amd64_ubuntu_jammy.deb
          path: debian/artifacts/clasp-cl_1.0.0_amd64.deb
      - uses: actions/upload-artifact@v3
        with:
          name: cando_1.0.0_amd64_ubuntu_jammy.deb
          path: debian/artifacts/cando_1.0.0_amd64.deb
  clasp_debian_bookworm:
    name: Clasp on Debian Bookworm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --build=binary --no-sign
          docker-image: debian:bookworm
          extra-build-deps: ca-certificates
      - uses: actions/upload-artifact@v3
        with:
          name: clasp-cl_1.0.0_amd64_debian_bookworm.deb
          path: debian/artifacts/clasp-cl_1.0.0_amd64.deb
      - uses: actions/upload-artifact@v3
        with:
          name: cando_1.0.0_amd64_debian_bookworm.deb
          path: debian/artifacts/cando_1.0.0_amd64.deb          