name: Nightly Packaging

on:
  push:
    branches: [ nightly ]
  schedule:
    - cron: '0 5 * * *'

jobs:
  clasp_ubuntu_jammy:
    name: Clasp on Ubuntu Jammy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update version
        run: |
          ./tools-for-build/nightly
      - name: Build Ubuntu packages
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --build=binary --no-sign
          docker-image: ubuntu:jammy
          extra-build-deps: ca-certificates netbase
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-jammy
          path: debian/artifacts/*.deb
  clasp_debian_bookworm:
    name: Clasp on Debian Bookworm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update version
        run: |
          ./tools-for-build/nightly
      - name: Build Debian packages
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --build=binary --no-sign
          docker-image: debian:bookworm
          extra-build-deps: ca-certificates netbase
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debian-bookworm
          path: debian/artifacts/*.deb
