name: Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: ${{ matrix.build }}@${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        build:
        - clasp
        - cando
        os:
        - macos-latest
        - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt install -y binutils-gold libbsd-dev clang-14 libclang-14-dev llvm-14 llvm-14-dev libelf-dev libgmp-dev libncurses-dev libunwind-dev ninja-build sbcl zlib1g-dev libnetcdf-dev libexpat1-dev libfmt-dev libboost-all-dev

    - name: Install MacOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install boost fmt gmp llvm@14 ninja pkg-config sbcl ecl netcdf expat
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      if: matrix.build == 'cando'

    - name: Install AmberTools
      if: matrix.build == 'cando'
      run: |
        conda install -c conda-forge ambertools

    - name: Clasp koga @ Ubuntu
      if: ${{ matrix.os == 'ubuntu-22.04' && matrix.build == 'clasp' }}
      run: |
        ./koga --no-clang-cpp --ldlibs=-ldl
    - name: Cando koga @ Ubuntu
      if: ${{ matrix.os == 'ubuntu-22.04' && matrix.build == 'cando' }}
      run: |
        ./koga --extensions=cando,seqan-clasp --no-clang-cpp --ldlibs=-ldl
    - name: Clasp koga @ MacOS
      if: ${{ matrix.os == 'macos-latest' && matrix.build == 'clasp' }}
      run: |
        ./koga
    - name: Cando koga @ MacOS
      if: ${{ matrix.os == 'macos-latest' && matrix.build == 'cando' }}
      run: |
        ./koga --extensions=cando,seqan-clasp
    - name: Build
      run: |
        ninja -C build
    - name: Run regression tests
      run: |
        ninja -C build test
    - name: Run ANSI tests
      if: ${{ matrix.build == 'clasp' }}
      run: |
        ninja -C build ansi-test
    - name: Run Cando regression tests
      if: ${{ matrix.build == 'cando' }}
      run: |
        ninja -C build cando-test
